env:
  commonjs: true
  es2020: true
  node: true
extends:
  - google
  - eslint:recommended
  - prettier
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: 11
plugins:
  - prettier
rules: {}
